language: python
install: pip install tox coveralls --use-mirrors
env:
  - TOX_ENV=py27_real
script:
  - tox -e $TOX_ENV
after_success: cd tests && coveralls
notifications:
  email:
    - jan.cespivo@gmail.com
