language: python
install: pip install tox coveralls --use-mirrors
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py26_cython
  - TOX_ENV=py27_cython
script:
  - tox -e $TOX_ENV
after_success: cd tests && coveralls
notifications:
  email:
    - jan.cespivo@gmail.com
