language: python
install: pip install tox coveralls --use-mirrors
env:
  - TOX_ENV=py26
  - TOX_ENV=py26_cython
  - TOX_ENV=py27
  - TOX_ENV=py27_cython
  - TOX_ENV=py33
  - TOX_ENV=py33_cython
  - TOX_ENV=py34
  - TOX_ENV=py34_cython
  - TOX_ENV=pypy
script:
  - tox -e $TOX_ENV
  - COVERAGE_FILE=tests/.coverage coverage report -m
after_success: coveralls
notifications:
  email:
    - jan.cespivo@gmail.com
